name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_pybind11_project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Master
      uses: actions/checkout@v3

    - name: Inspection
      run: |
          git clone https://github.com/pybind/pybind11.git ../forked_repo/pybind11
          chmod +x run_project.sh
          ./run_project.sh
