name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  Trial_GitHub_Action:
    runs-on: ubuntu-latest
    name: Sync stable with upstream latest

    steps:
    - name: Checkout Master
      uses: actions/checkout@v3
      with:
        ref: master

    - name: Inspection
      run: |
          echo "PWD"
          pwd
          echo "ls"
          ls
