name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_pybind11_project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Master
      uses: actions/checkout@v3

    - name: Build
      run: |
          pip install numpy
          git clone https://github.com/pybind/pybind11.git ../forked_repo/pybind11
          mkdir build && cd build
          cmake .. -DPYTHON_EXECUTABLE=$(which python) && make
          cd ../bin/

    - name: Execute
      run: |
          cd bin
          ./pybind_cpp_exec
          cd ..
          cp lib/*.so example/py/
          cd example/py/
          python3 main.py
          uname -a

    - name: Archive Files
      uses: actions/upload-artifact@v2
      with:
        name: deliverables
        path: |
          lib/*.so
          example/py/main.py

  deliver:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download Deliverables
      uses: actions/download-artifact@v2
      with:
        name: deliverables
        path: deliverables

    - name: List Deliverables
      run: |
        ls -la deliverables
        pwd
        ls
