name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  Trial_GitHub_Action:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Master
      uses: actions/checkout@v3

    - name: Inspection
      run: |
          echo "PWD"
          pwd
          sudo apt-get install tree
          tree
          echo "1 time tree done"
          chmod +x test_script.sh
          ./test_script.sh
